import { BEANIE_CONSTRUCTION, BEANIE_CONTROLS } from '../constructionCatalog'
import { garmentCapabilities } from '../capabilities'
import { attachSilhouettes } from '../topology'
import { FRONT_BACK_VIEWS, STANDARD_VIEWBOX } from '../types'
import type { GarmentDefinition, GarmentPanelDefinition } from '../types'
import { BEANIE_PATHS } from './geometry'

const FRONT_PRINT = {
  id: 'beanie_front_print',
  label: 'Front print',
  x: 18,
  y: 16,
  width: 64,
  height: 52,
}

const BACK_PRINT = {
  id: 'beanie_back_print',
  label: 'Back print',
  x: 20,
  y: 16,
  width: 60,
  height: 50,
}

export const BEANIE_PANELS: GarmentPanelDefinition[] = [
  {
    id: 'front_crown',
    name: 'Crown',
    label: 'Crown',
    viewId: 'front',
    side: 'front',
    type: 'crown',
    printable: true,
    local: { width: 100, height: 230 },
    frame: { x: 200, y: 166, width: 160, height: 242 },
    designBounds: { x: 18, y: 16, width: 64, height: 52 },
    designZones: [
      { id: 'beanie-front-full', name: 'Crown', bounds: { x: 0, y: 0, width: 100, height: 100 } },
      { id: 'beanie-front-print', name: 'Front print', bounds: { x: 18, y: 16, width: 64, height: 52 } },
    ],
    safeArea: FRONT_PRINT,
    placementZone: 'front',
    regionId: 'crown',
    regionLabel: 'Crown',
  },
  {
    id: 'back_crown',
    name: 'Back',
    label: 'Back',
    viewId: 'back',
    side: 'back',
    type: 'crown',
    printable: true,
    local: { width: 100, height: 230 },
    frame: { x: 200, y: 166, width: 160, height: 242 },
    designBounds: { x: 20, y: 16, width: 60, height: 50 },
    safeArea: BACK_PRINT,
    placementZone: 'back',
    regionId: 'back',
    regionLabel: 'Back',
  },
  {
    id: 'crown',
    name: 'Crown peak',
    label: 'Crown peak',
    viewId: 'front',
    side: 'front',
    type: 'crown',
    printable: false,
    local: { width: 180, height: 60 },
    frame: { x: 210, y: 154, width: 140, height: 46 },
    regionId: 'crown',
    regionLabel: 'Crown',
  },
  {
    id: 'crown_back',
    name: 'Crown peak',
    label: 'Crown peak',
    viewId: 'back',
    side: 'back',
    type: 'crown',
    printable: false,
    local: { width: 180, height: 60 },
    frame: { x: 210, y: 154, width: 140, height: 46 },
    regionId: 'back',
    regionLabel: 'Back',
  },
  {
    id: 'right_side',
    name: 'Right side',
    label: 'Right side',
    viewId: 'front',
    side: 'right',
    type: 'side_panel',
    printable: false,
    local: { width: 110, height: 230 },
    frame: { x: 146, y: 162, width: 122, height: 246 },
    regionId: 'right-side',
    regionLabel: 'Right side',
  },
  {
    id: 'left_side',
    name: 'Left side',
    label: 'Left side',
    viewId: 'front',
    side: 'left',
    type: 'side_panel',
    printable: false,
    local: { width: 110, height: 230 },
    frame: { x: 292, y: 162, width: 122, height: 246 },
    regionId: 'left-side',
    regionLabel: 'Left side',
  },
  {
    id: 'right_side_back',
    name: 'Right side',
    label: 'Right side',
    viewId: 'back',
    side: 'right',
    type: 'side_panel',
    printable: false,
    local: { width: 110, height: 230 },
    frame: { x: 292, y: 162, width: 122, height: 246 },
    regionId: 'right-side',
    regionLabel: 'Right side',
  },
  {
    id: 'left_side_back',
    name: 'Left side',
    label: 'Left side',
    viewId: 'back',
    side: 'left',
    type: 'side_panel',
    printable: false,
    local: { width: 110, height: 230 },
    frame: { x: 146, y: 162, width: 122, height: 246 },
    regionId: 'left-side',
    regionLabel: 'Left side',
  },
  {
    id: 'cuff',
    name: 'Cuff',
    label: 'Cuff',
    viewId: 'front',
    side: 'front',
    type: 'band',
    printable: false,
    local: { width: 270, height: 110 },
    frame: { x: 142, y: 392, width: 276, height: 120 },
    regionId: 'cuff',
    regionLabel: 'Cuff',
  },
  {
    id: 'cuff_back',
    name: 'Cuff',
    label: 'Cuff',
    viewId: 'back',
    side: 'back',
    type: 'band',
    printable: false,
    local: { width: 270, height: 110 },
    frame: { x: 142, y: 392, width: 276, height: 120 },
    regionId: 'cuff',
    regionLabel: 'Cuff',
  },
]

export function beanieDefaultPanelId(viewId: string): string {
  return viewId === 'back' ? 'back_crown' : 'front_crown'
}

export const beanieMeta = {
  id: 'beanie',
  name: 'Beanie',
  label: 'Beanie',
  category: 'headwear',
  views: FRONT_BACK_VIEWS,
  viewBox: STANDARD_VIEWBOX,
  panels: attachSilhouettes(BEANIE_PANELS, BEANIE_PATHS),
  regions: [
    { id: 'crown', label: 'Crown', panelIds: ['front_crown', 'crown'] },
    { id: 'cuff', label: 'Cuff', panelIds: ['cuff', 'cuff_back'] },
    { id: 'left-side', label: 'Left side', panelIds: ['left_side', 'left_side_back'] },
    { id: 'right-side', label: 'Right side', panelIds: ['right_side', 'right_side_back'] },
    { id: 'back', label: 'Back', panelIds: ['back_crown', 'crown_back'] },
  ],
  preview: { viewId: 'front' },
  supportedDesignZones: ['front', 'back'],
  constructionDefaults: BEANIE_CONSTRUCTION,
  constructionControls: BEANIE_CONTROLS,
  defaults: { bodyColor: '#3f4550' },
  capabilities: garmentCapabilities({
    printAreas: true,
    frontBack: true,
    hem: true,
    waistband: true,
    materials: true,
  }),
  defaultPanelId: beanieDefaultPanelId,
} satisfies Omit<GarmentDefinition, 'render'>
