import { CAP_CONSTRUCTION, CAP_CONTROLS } from '../constructionCatalog'
import { garmentCapabilities } from '../capabilities'
import { attachSilhouettes } from '../topology'
import { FRONT_BACK_VIEWS, STANDARD_VIEWBOX } from '../types'
import type { GarmentDefinition, GarmentPanelDefinition } from '../types'
import { CAP_PATHS } from './geometry'

const FRONT_PRINT = {
  id: 'cap_front_print',
  label: 'Front print',
  x: 16,
  y: 18,
  width: 68,
  height: 46,
}

const BACK_PRINT = {
  id: 'cap_back_print',
  label: 'Back print',
  x: 18,
  y: 18,
  width: 64,
  height: 44,
}

export const CAP_PANELS: GarmentPanelDefinition[] = [
  {
    id: 'front_panel',
    name: 'Front panel',
    label: 'Front panel',
    viewId: 'front',
    side: 'front',
    type: 'body',
    printable: true,
    local: { width: 100, height: 164 },
    frame: { x: 214, y: 208, width: 132, height: 168 },
    designBounds: { x: 16, y: 18, width: 68, height: 46 },
    designZones: [
      { id: 'cap-front-full', name: 'Front panel', bounds: { x: 0, y: 0, width: 100, height: 100 } },
      { id: 'cap-front-print', name: 'Front print', bounds: { x: 16, y: 18, width: 68, height: 46 } },
    ],
    safeArea: FRONT_PRINT,
    placementZone: 'front',
    regionId: 'front-panel',
    regionLabel: 'Front panel',
  },
  {
    id: 'back_panel',
    name: 'Back panel',
    label: 'Back panel',
    viewId: 'back',
    side: 'back',
    type: 'body',
    printable: true,
    local: { width: 100, height: 164 },
    frame: { x: 214, y: 208, width: 132, height: 168 },
    designBounds: { x: 18, y: 18, width: 64, height: 44 },
    safeArea: BACK_PRINT,
    placementZone: 'back',
    regionId: 'back-panel',
    regionLabel: 'Back panel',
  },
  {
    id: 'crown',
    name: 'Crown',
    label: 'Crown',
    viewId: 'front',
    side: 'front',
    type: 'crown',
    printable: false,
    local: { width: 200, height: 88 },
    frame: { x: 196, y: 196, width: 168, height: 50 },
    regionId: 'crown',
    regionLabel: 'Crown',
  },
  {
    id: 'crown_back',
    name: 'Crown',
    label: 'Crown',
    viewId: 'back',
    side: 'back',
    type: 'crown',
    printable: false,
    local: { width: 200, height: 88 },
    frame: { x: 196, y: 196, width: 168, height: 50 },
    regionId: 'crown',
    regionLabel: 'Crown',
  },
  {
    id: 'right_side',
    name: 'Right side',
    label: 'Right side',
    viewId: 'front',
    side: 'right',
    type: 'side_panel',
    printable: false,
    local: { width: 92, height: 190 },
    frame: { x: 140, y: 202, width: 128, height: 174 },
    regionId: 'right-side',
    regionLabel: 'Right side',
  },
  {
    id: 'left_side',
    name: 'Left side',
    label: 'Left side',
    viewId: 'front',
    side: 'left',
    type: 'side_panel',
    printable: false,
    local: { width: 92, height: 190 },
    frame: { x: 292, y: 202, width: 128, height: 174 },
    regionId: 'left-side',
    regionLabel: 'Left side',
  },
  {
    id: 'right_side_back',
    name: 'Right side',
    label: 'Right side',
    viewId: 'back',
    side: 'right',
    type: 'side_panel',
    printable: false,
    local: { width: 92, height: 190 },
    frame: { x: 292, y: 202, width: 128, height: 174 },
    regionId: 'right-side',
    regionLabel: 'Right side',
  },
  {
    id: 'left_side_back',
    name: 'Left side',
    label: 'Left side',
    viewId: 'back',
    side: 'left',
    type: 'side_panel',
    printable: false,
    local: { width: 92, height: 190 },
    frame: { x: 140, y: 202, width: 128, height: 174 },
    regionId: 'left-side',
    regionLabel: 'Left side',
  },
  {
    id: 'brim',
    name: 'Brim',
    label: 'Brim',
    viewId: 'front',
    side: 'front',
    type: 'brim',
    printable: false,
    local: { width: 352, height: 140 },
    frame: { x: 104, y: 364, width: 352, height: 124 },
    regionId: 'brim',
    regionLabel: 'Brim',
  },
  {
    id: 'band',
    name: 'Band',
    label: 'Band',
    viewId: 'front',
    side: 'front',
    type: 'band',
    printable: false,
    local: { width: 228, height: 42 },
    frame: { x: 146, y: 360, width: 268, height: 46 },
    regionId: 'band',
    regionLabel: 'Band',
  },
  {
    id: 'band_back',
    name: 'Band',
    label: 'Band',
    viewId: 'back',
    side: 'back',
    type: 'band',
    printable: false,
    local: { width: 228, height: 42 },
    frame: { x: 146, y: 360, width: 268, height: 46 },
    regionId: 'band',
    regionLabel: 'Band',
  },
  {
    id: 'closure',
    name: 'Closure',
    label: 'Closure',
    viewId: 'back',
    side: 'back',
    type: 'structure',
    printable: false,
    local: { width: 104, height: 40 },
    frame: { x: 224, y: 346, width: 112, height: 66 },
    regionId: 'closure',
    regionLabel: 'Closure',
  },
]

export function capDefaultPanelId(viewId: string): string {
  return viewId === 'back' ? 'back_panel' : 'front_panel'
}

export const capMeta = {
  id: 'cap',
  name: 'Cap',
  label: 'Cap',
  category: 'headwear',
  views: FRONT_BACK_VIEWS,
  viewBox: STANDARD_VIEWBOX,
  panels: attachSilhouettes(CAP_PANELS, CAP_PATHS),
  regions: [
    { id: 'crown', label: 'Crown', panelIds: ['crown', 'crown_back'] },
    { id: 'front-panel', label: 'Front panel', panelIds: ['front_panel'] },
    { id: 'left-side', label: 'Left side', panelIds: ['left_side', 'left_side_back'] },
    { id: 'right-side', label: 'Right side', panelIds: ['right_side', 'right_side_back'] },
    { id: 'back-panel', label: 'Back panel', panelIds: ['back_panel'] },
    { id: 'brim', label: 'Brim', panelIds: ['brim'] },
    { id: 'band', label: 'Band', panelIds: ['band', 'band_back'] },
    { id: 'closure', label: 'Closure', panelIds: ['closure'] },
  ],
  preview: { viewId: 'front' },
  supportedDesignZones: ['front', 'back'],
  constructionDefaults: CAP_CONSTRUCTION,
  constructionControls: CAP_CONTROLS,
  defaults: { bodyColor: '#3a4452' },
  capabilities: garmentCapabilities({
    printAreas: true,
    frontBack: true,
    hem: true,
    waistband: true,
    buttons: true,
    materials: true,
  }),
  defaultPanelId: capDefaultPanelId,
} satisfies Omit<GarmentDefinition, 'render'>
