import { garmentCapabilities } from '../capabilities'
import { FRONT_BACK_VIEWS, STANDARD_VIEWBOX } from '../types'
import type { GarmentDefinition, GarmentPanelDefinition } from '../types'

const CHEST_PRINT = {
  id: 'sweatshirt_chest_print',
  label: 'Chest print',
  x: 24,
  y: 36,
  width: 152,
  height: 120,
}

const BACK_PRINT = {
  id: 'sweatshirt_back_print',
  label: 'Back print',
  x: 20,
  y: 28,
  width: 160,
  height: 180,
}

const SLEEVE_PRINT = {
  id: 'sweatshirt_sleeve_print',
  label: 'Sleeve print',
  x: 16,
  y: 18,
  width: 78,
  height: 90,
}

function sleevePrint(id: string): GarmentPanelDefinition['safeArea'] {
  return { ...SLEEVE_PRINT, id }
}

export const SWEATSHIRT_PANELS: GarmentPanelDefinition[] = [
  {
    id: 'front_body',
    name: 'Front body',
    label: 'Front body',
    viewId: 'front',
    side: 'front',
    type: 'body',
    printable: true,
    local: { width: 200, height: 300 },
    frame: { x: 174, y: 200, width: 212, height: 342 },
    designBounds: { x: 12, y: 12, width: 76, height: 40 },
    designZones: [
      { id: 'sweatshirt-full-front', name: 'Front print', bounds: { x: 0, y: 0, width: 100, height: 100 } },
      { id: 'sweatshirt-chest', name: 'Chest', bounds: { x: 12, y: 12, width: 76, height: 40 } },
      { id: 'sweatshirt-center-front', name: 'Center front', bounds: { x: 30, y: 20, width: 40, height: 40 } },
    ],
    safeArea: CHEST_PRINT,
  },
  {
    id: 'back_body',
    name: 'Back body',
    label: 'Back body',
    viewId: 'back',
    side: 'back',
    type: 'body',
    printable: true,
    local: { width: 200, height: 320 },
    frame: { x: 174, y: 190, width: 212, height: 352 },
    designBounds: { x: 10, y: 8.75, width: 80, height: 56.25 },
    designZones: [
      { id: 'sweatshirt-full-back', name: 'Back print', bounds: { x: 0, y: 0, width: 100, height: 100 } },
      { id: 'sweatshirt-upper-back', name: 'Upper back', bounds: { x: 10, y: 8.75, width: 80, height: 40 } },
    ],
    safeArea: BACK_PRINT,
  },
  {
    id: 'right_sleeve',
    name: 'Right sleeve',
    label: 'Right sleeve',
    viewId: 'front',
    side: 'right',
    type: 'sleeve',
    printable: true,
    local: { width: 110, height: 160 },
    frame: { x: 32, y: 180, width: 142, height: 186 },
    designBounds: { x: 14.55, y: 11.25, width: 70.91, height: 56.25 },
    designZones: [
      { id: 'sweatshirt-right-outer-sleeve', name: 'Right sleeve', bounds: { x: 0, y: 0, width: 100, height: 100 } },
      { id: 'sweatshirt-right-sleeve-center', name: 'Sleeve center', bounds: { x: 14.55, y: 11.25, width: 70.91, height: 56.25 } },
    ],
    safeArea: sleevePrint('sweatshirt_right_sleeve_print'),
  },
  {
    id: 'left_sleeve',
    name: 'Left sleeve',
    label: 'Left sleeve',
    viewId: 'front',
    side: 'left',
    type: 'sleeve',
    printable: true,
    local: { width: 110, height: 160 },
    frame: { x: 386, y: 180, width: 142, height: 186 },
    designBounds: { x: 14.55, y: 11.25, width: 70.91, height: 56.25 },
    designZones: [
      { id: 'sweatshirt-left-outer-sleeve', name: 'Left sleeve', bounds: { x: 0, y: 0, width: 100, height: 100 } },
      { id: 'sweatshirt-left-sleeve-center', name: 'Sleeve center', bounds: { x: 14.55, y: 11.25, width: 70.91, height: 56.25 } },
    ],
    safeArea: sleevePrint('sweatshirt_left_sleeve_print'),
  },
  {
    id: 'collar',
    name: 'Collar',
    label: 'Collar',
    viewId: 'front',
    side: 'front',
    type: 'collar',
    printable: false,
    local: { width: 120, height: 48 },
    frame: { x: 220, y: 168, width: 120, height: 48 },
  },
  {
    id: 'right_sleeve_back',
    name: 'Right sleeve',
    label: 'Right sleeve',
    viewId: 'back',
    side: 'right',
    type: 'sleeve',
    printable: true,
    local: { width: 110, height: 160 },
    frame: { x: 386, y: 180, width: 142, height: 186 },
    designBounds: { x: 14.55, y: 11.25, width: 70.91, height: 56.25 },
    safeArea: sleevePrint('sweatshirt_right_sleeve_back_print'),
  },
  {
    id: 'left_sleeve_back',
    name: 'Left sleeve',
    label: 'Left sleeve',
    viewId: 'back',
    side: 'left',
    type: 'sleeve',
    printable: true,
    local: { width: 110, height: 160 },
    frame: { x: 32, y: 180, width: 142, height: 186 },
    designBounds: { x: 14.55, y: 11.25, width: 70.91, height: 56.25 },
    safeArea: sleevePrint('sweatshirt_left_sleeve_back_print'),
  },
  {
    id: 'collar_back',
    name: 'Collar',
    label: 'Collar',
    viewId: 'back',
    side: 'back',
    type: 'collar',
    printable: false,
    local: { width: 120, height: 40 },
    frame: { x: 224, y: 172, width: 112, height: 40 },
  },
  {
    id: 'cuff_right',
    name: 'Right cuff',
    label: 'Right cuff',
    viewId: 'front',
    side: 'right',
    type: 'cuff',
    printable: false,
    local: { width: 60, height: 40 },
    frame: { x: 26, y: 356, width: 58, height: 52 },
  },
  {
    id: 'cuff_left',
    name: 'Left cuff',
    label: 'Left cuff',
    viewId: 'front',
    side: 'left',
    type: 'cuff',
    printable: false,
    local: { width: 60, height: 40 },
    frame: { x: 476, y: 356, width: 58, height: 52 },
  },
  {
    id: 'cuff_right_back',
    name: 'Right cuff',
    label: 'Right cuff',
    viewId: 'back',
    side: 'right',
    type: 'cuff',
    printable: false,
    local: { width: 60, height: 40 },
    frame: { x: 476, y: 356, width: 58, height: 52 },
  },
  {
    id: 'cuff_left_back',
    name: 'Left cuff',
    label: 'Left cuff',
    viewId: 'back',
    side: 'left',
    type: 'cuff',
    printable: false,
    local: { width: 60, height: 40 },
    frame: { x: 26, y: 356, width: 58, height: 52 },
  },
]

export function sweatshirtDefaultPanelId(viewId: string): string {
  return viewId === 'back' ? 'back_body' : 'front_body'
}

export const sweatshirtMeta = {
  id: 'sweatshirt',
  name: 'Sweatshirt',
  label: 'Sweatshirt',
  category: 'tops',
  views: FRONT_BACK_VIEWS,
  viewBox: STANDARD_VIEWBOX,
  panels: SWEATSHIRT_PANELS,
  preview: { viewId: 'front' },
  supportedDesignZones: ['front', 'back', 'left-sleeve', 'right-sleeve'],
  defaults: { bodyColor: '#4a3f38' },
  capabilities: garmentCapabilities({
    sleeves: true,
    collar: true,
    cuffs: true,
    hem: true,
    printAreas: true,
    frontBack: true,
  }),
  defaultPanelId: sweatshirtDefaultPanelId,
} satisfies Omit<GarmentDefinition, 'render'>
